lunchReservation/config/routes.rb
LunchReservation::Application.routes.draw do
  resources :reserve_lists

end

lunchReservation/app/models/reserve_list.rb
class ReserveList < ActiveRecord::Base
  attr_accessible :id, :lunch, :name, :note, :price
end

lunchReservation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

lunchReservation/app/controllers/reserve_lists_controller.rb
class ReserveListsController < ApplicationController
  # GET /reserve_lists
  # GET /reserve_lists.json
  def index
    @reserve_lists = ReserveList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reserve_lists }
    end
  end

  # GET /reserve_lists/1
  # GET /reserve_lists/1.json
  def show
    @reserve_list = ReserveList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reserve_list }
    end
  end

  # GET /reserve_lists/new
  # GET /reserve_lists/new.json
  def new
    @reserve_list = ReserveList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reserve_list }
    end
  end

  # GET /reserve_lists/1/edit
  def edit
    @reserve_list = ReserveList.find(params[:id])
  end

  # POST /reserve_lists
  # POST /reserve_lists.json
  def create
    @reserve_list = ReserveList.new(params[:reserve_list])

    respond_to do |format|
      if @reserve_list.save
        format.html { redirect_to @reserve_list, notice: 'Reserve list was successfully created.' }
        format.json { render json: @reserve_list, status: :created, location: @reserve_list }
      else
        format.html { render action: "new" }
        format.json { render json: @reserve_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reserve_lists/1
  # PUT /reserve_lists/1.json
  def update
    @reserve_list = ReserveList.find(params[:id])

    respond_to do |format|
      if @reserve_list.update_attributes(params[:reserve_list])
        format.html { redirect_to @reserve_list, notice: 'Reserve list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reserve_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserve_lists/1
  # DELETE /reserve_lists/1.json
  def destroy
    @reserve_list = ReserveList.find(params[:id])
    @reserve_list.destroy

    respond_to do |format|
      format.html { redirect_to reserve_lists_url }
      format.json { head :no_content }
    end
  end
end

lunchReservation/app/helpers/application_helper.rb
module ApplicationHelper
end

lunchReservation/app/helpers/reserve_lists_helper.rb
module ReserveListsHelper
end

lunchReservation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LunchReservation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

lunchReservation/app/views/reserve_lists/_form.html.erb
<%= form_for(@reserve_list) do |f| %>
  <% if @reserve_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserve_list.errors.count, "error") %> prohibited this reserve_list from being saved:</h2>

      <ul>
      <% @reserve_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lunch %><br />
    <%= f.text_field :lunch %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lunchReservation/app/views/reserve_lists/edit.html.erb
<h1>Editing reserve_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @reserve_list %> |
<%= link_to 'Back', reserve_lists_path %>

lunchReservation/app/views/reserve_lists/index.html.erb
<h1>Listing reserve_lists</h1>

<table>
  <tr>
    <th>Id</th>
    <th>姓名</th>
    <th>餐點</th>
    <th>備註</th>
    <th>價格</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reserve_lists.each do |reserve_list| %>
  <tr>
    <td><%= reserve_list.id %></td>
    <td><%= reserve_list.name %></td>
    <td><%= reserve_list.lunch %></td>
    <td><%= reserve_list.note %></td>
    <td><%= reserve_list.price %></td>
    <td><%= link_to 'Show', reserve_list %></td>
    <td><%= link_to 'Edit', edit_reserve_list_path(reserve_list) %></td>
    <td><%= link_to 'Destroy', reserve_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reserve list', new_reserve_list_path %>

lunchReservation/app/views/reserve_lists/new.html.erb
<h1>New reserve_list</h1>

<%= render 'form' %>

<%= link_to 'Back', reserve_lists_path %>

lunchReservation/app/views/reserve_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @reserve_list.id %>
</p>

<p>
  <b>Name:</b>
  <%= @reserve_list.name %>
</p>

<p>
  <b>Lunch:</b>
  <%= @reserve_list.lunch %>
</p>

<p>
  <b>Note:</b>
  <%= @reserve_list.note %>
</p>

<p>
  <b>Price:</b>
  <%= @reserve_list.price %>
</p>


<%= link_to 'Edit', edit_reserve_list_path(@reserve_list) %> |
<%= link_to 'Back', reserve_lists_path %>